variables:
  TEST_URL: "https://test.ltc.bcit.ca"
  PROD_URL: "https://ltc.bcit.ca"
  WEB_ROOT: "/var/www/html"

# 2 Stage process: build > deploy
stages:
  - build
  - deploy

# Stage 1: build
build:
  only:
    refs:
      # - production
      - staging
  stage: build
  script:
    - echo "Installing npm"
    - npm install
    - echo "Building the application"
    - npm run build
    - echo "Build Ready"
  artifacts:
    paths:
      - build/

# Stage 2: Deploying on staging environment
deploy_staging:
  only:
    refs:
      - staging
  stage: deploy
  script:
    - mkdir -p "$WEB_ROOT/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
    - cd build && rsync -av --delete . $WEB_ROOT/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  environment:
    name: staging
    url: "$TEST_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  tags:
    - old-staging 

# Stage 2: Deploying on production environment
deploy_production:
  only:
    refs:
      - production
  stage: deploy
  script:
    - mkdir -p "$WEB_ROOT/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
    - cd build && rsync -av --delete . $WEB_ROOT/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  environment:
    name: production
    url: "$PROD_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  tags:
    - old-production 
