version: "3"

services:
  app:
    build: 
      context: .
    # command: >
    #   sh -c "
    #   (cd /code && npm install)
    #   && (cd /code && npm run build)"
    image: qfpcr
    environment:
      - DEBUG=True
    restart: always
    # volumes:
    #   - .:/code
    ports:
      - "9000:9000"