import React, { Component } from 'react';
import { Image } from 'react-bootstrap';
import NormalMale from '../assets/normalMale.JPG'

class IntroductionPage extends Component {

    constructor(props) {
        super(props);
        this.state = {
            show: false
        }
    }

    render() {
        return (
            <div style={{ height: '100%', minHeight: '100vh' }} className="d-flex flex-column justify-content-start mt-4 align-items-start col-12 text-dark">

                <div style={{ fontSize: '1.2rem', height: '100%' }} className="d-flex col-sm-11 flex-column align-items-start bg-white ">
                    <h3 className="text-info text-monospace" style={{ letterSpacing: 1 }}>Introduction:</h3>
                    <p className="mt-2">Welcome to the Quantitative fluorescence PCR (QF-PCR) online learning module. Are you interested in learning more about Quantitative Fluorescence PCR as method for rapid aneuploidy detection ? Curious to learn how to analysis the data generated by this procedure ? This self-directed introduction/practice resource is for you. At the end of the resource,  you will have the option to completea a final assessment to obtain a certificate of completion. </p>
                </div>
                <span className="d-flex flex-column col-sm-11 mt-3 align-items-center">
                    <Image
                        style={{maxWidth:1000,width:"100%"}}
                        src={NormalMale} 
                        alt = 'Normal Male Results'
                    />
                    <h5>An Example of normal male results</h5>
                </span>

            </div>
        )
    }
}

export default IntroductionPage;